apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-operator-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "tetragon-operator.labels" . | nindent 4 }}
data:
  skip-crd-creation: {{ .Values.tetragonOperator.skipCRDCreation | quote }}
  skip-tetragon-pod-crd: {{ not .Values.podWatcher.enabled | quote }}
